In [ ]:
    import numpy as np
    A = np.matrix(
        [[1, 5, 3],
        [4, 6, 6],
        [3, 8, 9]])
    B = np.matrix(
        [[1, 5, 3, 4],
        [4, 5, 7, 8],
        [7, 8, 9, 3]])
    C = np.matrix(
        [[1],
        [4],
        [3]])
    D = np.matrix(
        [[1, 5, 3]])
    result_AB = np.matmul(A, B)  
    result_BA = np.matmul(B.T, A) 
    print("Result of A * B:\n", result_AB)
    print("Result of B * A:\n", result_BA)


Result of A * B:
 [[ 42  54  65  53]
 [ 70  98 108  82]
 [ 98 127 146 103]]
Result of B * A:
 [[ 38  85  90]
 [ 49 119 117]
 [ 58 129 132]
 [ 45  92  87]]
